apiVersion: v1
kind: Service
metadata:
  name: ai-engine
  labels:
    app: ai-engine
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  type: ClusterIP
  selector:
    app: ai-engine
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
