apiVersion: v1
kind: Namespace
metadata:
  name: self-heal-system
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-payment
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-checkout
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
